In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/psrc0514/wifi-identification/wifi_measurements.csv
/kaggle/input/datasets/psrc0514/responses/Responses - Form responses 1.csv

In [4]:
import pandas as pd

survey = pd.read_csv("/kaggle/input/datasets/psrc0514/responses/Responses - Form responses 1.csv")

print(survey.shape)
display(survey.head())

(74, 6)

,Timestamp,How frequently do you face Wi-Fi/connectivity issues on campus?,What kind of network problems do you face most often?,Where do you face these problems most frequently?,How does poor connectivity affect you?,What would you find most useful in a better campus Wi-Fi system?
0,25/09/2026 21:08:20,Almost every day,Slow internet speed,Hostel room,Assignments/project work,A live campus Wi-Fi coverage/quality map
1,25/09/2026 21:13:46,Almost every day,Slow internet speed,EVERYWHERE,Downloading/uploading files,A live campus Wi-Fi coverage/quality map
2,25/09/2026 21:17:36,Almost every day,Unable to connect to Wi-Fi,Academic buildings/classrooms,Assignments/project work,Automatically detecting network issues and not...
3,25/09/2026 21:23:49,Almost every day,All,Hostel room,All,All
4,25/09/2026 21:27:34,Almost every day,Every option of above,Every above option,Every above option,A better wifi

In [5]:
survey.columns = [
    "timestamp",
    "frequency",
    "problem_type",
    "location",
    "impact",
    "desired_solution"
]

survey["location"] = (
    survey["location"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [6]:
def normalize_location(x):

    if "hostel room" in x:
        return "HOSTEL ROOM"

    if "hostel common" in x:
        return "HOSTEL COMMON AREA"

    if "academic" in x or "classroom" in x:
        return "ACADEMIC BUILDINGS"

    if "library" in x:
        return "LIBRARY"

    if "mess" in x or "canteen" in x:
        return "MESS / CANTEEN"

    if "new sac" in x:
        return "NEW SAC"

    if "everywhere" in x or "every above" in x or "all places" in x:
        return "EVERYWHERE"

    return "OTHER"

survey["location_group"] = survey["location"].apply(
    normalize_location
)

In [7]:
location_survey = (
    survey
    .groupby("location_group")
    .size()
    .reset_index(name="responses")
    .sort_values("responses", ascending=False)
)

display(location_survey)

       location_group  responses
3         HOSTEL ROOM         45
0  ACADEMIC BUILDINGS          9
2  HOSTEL COMMON AREA          8
1          EVERYWHERE          4
4             LIBRARY          3
6               OTHER          3
5      MESS / CANTEEN          2

In [8]:
problem_survey = (
    survey
    .groupby("problem_type")
    .size()
    .reset_index(name="responses")
    .sort_values("responses", ascending=False)
)

display(problem_survey)

                                        problem_type  responses
5                                Slow internet speed         31
7                         Unable to connect to Wi-Fi         18
3                             Frequent disconnection         12
1                                   All of the above          4
4  High latency/ping during calls or online activ...          3
0                                                All          2
2                              Every option of above          1
6  Some legal and study related  websites which a...          1
8                                   all of the above          1
9                             all of these problems!          1

In [9]:
solution_demand = (
    survey
    .groupby("desired_solution")
    .size()
    .reset_index(name="responses")
    .sort_values("responses", ascending=False)
)

display(solution_demand)

                                     desired_solution  responses
1            A live campus Wi-Fi coverage/quality map         32
2   A way to report network problems with location...         13
4   Automatically detecting network issues and not...         11
6   Identifying locations with recurring network p...          6
9   Knowing which areas currently have better conn...          4
3                                                 All          1
0                                       A better wifi          1
7                                It should just work.          1
5                                   Better wifi speed          1
8   Just increase the network speed that's the onl...          1
10  Predicting when/where congestion is likely to ...          1
11                                   all of the above          1
12  cant you guys just make ur connection better i...          1

In [10]:
print(survey.columns.tolist())

['timestamp', 'frequency', 'problem_type', 'location', 'impact', 'desired_solution', 'location_group']

In [11]:
print("Variables currently available:")
print(list(globals().keys()))

Variables currently available:
['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', '_', '__', '___', '_i', '_ii', '_iii', '_i1', '_i2', '_i3', 'np', 'pd', 'os', 'dirname', 'filenames', 'filename', 'kagglehub', '_i4', 'survey', '_i5', '_i6', 'normalize_location', '_i7', 'location_survey', '_i8', 'problem_survey', '_i9', 'solution_demand', '_i10', '_i11']

In [12]:
display(location_survey)

       location_group  responses
3         HOSTEL ROOM         45
0  ACADEMIC BUILDINGS          9
2  HOSTEL COMMON AREA          8
1          EVERYWHERE          4
4             LIBRARY          3
6               OTHER          3
5      MESS / CANTEEN          2

In [13]:
display(problem_survey)

                                        problem_type  responses
5                                Slow internet speed         31
7                         Unable to connect to Wi-Fi         18
3                             Frequent disconnection         12
1                                   All of the above          4
4  High latency/ping during calls or online activ...          3
0                                                All          2
2                              Every option of above          1
6  Some legal and study related  websites which a...          1
8                                   all of the above          1
9                             all of these problems!          1

In [14]:
display(solution_demand)

                                     desired_solution  responses
1            A live campus Wi-Fi coverage/quality map         32
2   A way to report network problems with location...         13
4   Automatically detecting network issues and not...         11
6   Identifying locations with recurring network p...          6
9   Knowing which areas currently have better conn...          4
3                                                 All          1
0                                       A better wifi          1
7                                It should just work.          1
5                                   Better wifi speed          1
8   Just increase the network speed that's the onl...          1
10  Predicting when/where congestion is likely to ...          1
11                                   all of the above          1
12  cant you guys just make ur connection better i...          1

In [15]:
location_profile = (
    survey
    .groupby("location_group")
    .agg(
        survey_responses=("location_group", "size")
    )
    .reset_index()
)

display(location_profile)

       location_group  survey_responses
0  ACADEMIC BUILDINGS                 9
1          EVERYWHERE                 4
2  HOSTEL COMMON AREA                 8
3         HOSTEL ROOM                45
4             LIBRARY                 3
5      MESS / CANTEEN                 2
6               OTHER                 3

In [16]:
frequency_profile = (
    survey
    .groupby(["location_group", "frequency"])
    .size()
    .reset_index(name="count")
)

display(frequency_profile)

        location_group             frequency  count
0   ACADEMIC BUILDINGS      Almost every day      6
1   ACADEMIC BUILDINGS  Several times a week      3
2           EVERYWHERE      Almost every day      4
3   HOSTEL COMMON AREA      Almost every day      8
4          HOSTEL ROOM      Almost every day     36
5          HOSTEL ROOM                Rarely      3
6          HOSTEL ROOM  Several times a week      6
7              LIBRARY      Almost every day      3
8       MESS / CANTEEN      Almost every day      1
9       MESS / CANTEEN  Several times a week      1
10               OTHER      Almost every day      3

In [17]:
problem_profile = (
    survey
    .groupby(["location_group", "problem_type"])
    .size()
    .reset_index(name="count")
)

display(problem_profile)

,location_group,problem_type,count
0,ACADEMIC BUILDINGS,Frequent disconnection,1
1,ACADEMIC BUILDINGS,Slow internet speed,3
2,ACADEMIC BUILDINGS,Unable to connect to Wi-Fi,4
3,ACADEMIC BUILDINGS,all of these problems!,1
4,EVERYWHERE,All of the above,2
5,EVERYWHERE,Every option of above,1
6,EVERYWHERE,Slow internet speed,1
7,HOSTEL COMMON AREA,Frequent disconnection,2
8,HOSTEL COMMON AREA,Slow internet speed,3
9,HOSTEL COMMON AREA,Unable to connect to Wi-Fi,3
10,HOSTEL ROOM,All,1
11,HOSTEL ROOM,All of the above,2
12,HOSTEL ROOM,Frequent disconnection,7
13,HOSTEL ROOM,High latency/ping during calls or online activ...,3
14,HOSTEL ROOM,Slow internet speed,22
15,HOSTEL ROOM,Some legal and study related websites which a...,1
16,HOSTEL ROOM,Unable to connect to Wi-Fi,9
17,LIBRARY,Slow internet speed,1
18,LIBRARY,Unable to connect to Wi-Fi,2
19,MESS / CANTEEN,Frequent disconnection,2
20,OTHER,All,1
21,OTHER,Slow internet speed,1
22,OTHER,all of the above,1

In [18]:
impact_profile = (
    survey
    .groupby(["location_group", "impact"])
    .size()
    .reset_index(name="count")
)

display(impact_profile)

        location_group                                    impact  count
0   ACADEMIC BUILDINGS                  Assignments/project work      4
1   ACADEMIC BUILDINGS               Downloading/uploading files      3
2   ACADEMIC BUILDINGS  Everything because internet doesn't work      1
3   ACADEMIC BUILDINGS              Online classes/academic work      1
4           EVERYWHERE                        Coding/development      1
5           EVERYWHERE               Downloading/uploading files      1
6           EVERYWHERE                        Every above option      1
7           EVERYWHERE                         It kills the vibe      1
8   HOSTEL COMMON AREA                  Assignments/project work      3
9   HOSTEL COMMON AREA                        Coding/development      1
10  HOSTEL COMMON AREA               Downloading/uploading files      1
11  HOSTEL COMMON AREA              Online classes/academic work      3
12         HOSTEL ROOM                                       All      2
13         HOSTEL ROOM                  Assignments/project work     14
14         HOSTEL ROOM                        Coding/development      5
15         HOSTEL ROOM               Downloading/uploading files      6
16         HOSTEL ROOM              Online classes/academic work     10
17         HOSTEL ROOM                  Online events/hackathons      5
18         HOSTEL ROOM             Streaming/content consumption      1
19         HOSTEL ROOM                      Video calls/meetings      2
20             LIBRARY                  Assignments/project work      1
21             LIBRARY               Downloading/uploading files      1
22             LIBRARY              Online classes/academic work      1
23      MESS / CANTEEN                  Online events/hackathons      1
24      MESS / CANTEEN             Streaming/content consumption      1
25               OTHER                  Assignments/project work      1
26               OTHER                        Coding/development      1
27               OTHER                          all of the above      1

In [19]:
print("Location examples:")
display(survey["location"].head(20))

print("\nProblem examples:")
display(survey["problem_type"].head(20))

print("\nFrequency examples:")
display(survey["frequency"].head(20))

print("\nImpact examples:")
display(survey["impact"].head(20))

Location examples:

0                       hostel room
1                        everywhere
2     academic buildings/classrooms
3                       hostel room
4                every above option
5                       hostel room
6                      mess/canteen
7     academic buildings/classrooms
8                hostel common area
9                       hostel room
10    academic buildings/classrooms
11                       all places
12                      hostel room
13                      hostel room
14                      hostel room
15                      hostel room
16                      hostel room
17    academic buildings/classrooms
18                      hostel room
19                      hostel room
Name: location, dtype: object

Problem examples:

0            Slow internet speed
1            Slow internet speed
2     Unable to connect to Wi-Fi
3                            All
4          Every option of above
5     Unable to connect to Wi-Fi
6         Frequent disconnection
7     Unable to connect to Wi-Fi
8         Frequent disconnection
9         Frequent disconnection
10           Slow internet speed
11              All of the above
12           Slow internet speed
13    Unable to connect to Wi-Fi
14    Unable to connect to Wi-Fi
15           Slow internet speed
16        Frequent disconnection
17    Unable to connect to Wi-Fi
18           Slow internet speed
19           Slow internet speed
Name: problem_type, dtype: object

Frequency examples:

0         Almost every day
1         Almost every day
2         Almost every day
3         Almost every day
4         Almost every day
5     Several times a week
6         Almost every day
7     Several times a week
8         Almost every day
9         Almost every day
10        Almost every day
11        Almost every day
12        Almost every day
13        Almost every day
14        Almost every day
15        Almost every day
16        Almost every day
17    Several times a week
18                  Rarely
19        Almost every day
Name: frequency, dtype: object

Impact examples:

0                     Assignments/project work
1                  Downloading/uploading files
2                     Assignments/project work
3                                          All
4                           Every above option
5                     Assignments/project work
6                     Online events/hackathons
7                  Downloading/uploading files
8                 Online classes/academic work
9                  Downloading/uploading files
10                 Downloading/uploading files
11                          Coding/development
12                 Downloading/uploading files
13                Online classes/academic work
14                Online classes/academic work
15                    Assignments/project work
16                Online classes/academic work
17    Everything because internet doesn't work
18                 Downloading/uploading files
19                 Downloading/uploading files
Name: impact, dtype: object

In [20]:
def expand_location(x):
    x = str(x).strip().lower()

    if x in ["everywhere", "every above option", "all places"]:
        return [
            "HOSTEL ROOM",
            "HOSTEL COMMON AREA",
            "ACADEMIC BUILDINGS",
            "LIBRARY",
            "MESS / CANTEEN"
        ]

    if "hostel room" in x:
        return ["HOSTEL ROOM"]

    if "hostel common" in x:
        return ["HOSTEL COMMON AREA"]

    if "academic" in x or "classroom" in x:
        return ["ACADEMIC BUILDINGS"]

    if "library" in x:
        return ["LIBRARY"]

    if "mess" in x or "canteen" in x:
        return ["MESS / CANTEEN"]

    return ["OTHER"]

In [21]:
survey_location = survey.copy()

survey_location["location_group"] = survey_location["location"].apply(
    expand_location
)

survey_location = survey_location.explode("location_group")

display(
    survey_location[
        ["location", "location_group", "frequency", "problem_type", "impact"]
    ].head(20)
)

,location,location_group,frequency,problem_type,impact
0,hostel room,HOSTEL ROOM,Almost every day,Slow internet speed,Assignments/project work
1,everywhere,HOSTEL ROOM,Almost every day,Slow internet speed,Downloading/uploading files
1,everywhere,HOSTEL COMMON AREA,Almost every day,Slow internet speed,Downloading/uploading files
1,everywhere,ACADEMIC BUILDINGS,Almost every day,Slow internet speed,Downloading/uploading files
1,everywhere,LIBRARY,Almost every day,Slow internet speed,Downloading/uploading files
1,everywhere,MESS / CANTEEN,Almost every day,Slow internet speed,Downloading/uploading files
2,academic buildings/classrooms,ACADEMIC BUILDINGS,Almost every day,Unable to connect to Wi-Fi,Assignments/project work
3,hostel room,HOSTEL ROOM,Almost every day,All,All
4,every above option,HOSTEL ROOM,Almost every day,Every option of above,Every above option
4,every above option,HOSTEL COMMON AREA,Almost every day,Every option of above,Every above option
4,every above option,ACADEMIC BUILDINGS,Almost every day,Every option of above,Every above option
4,every above option,LIBRARY,Almost every day,Every option of above,Every above option
4,every above option,MESS / CANTEEN,Almost every day,Every option of above,Every above option
5,hostel room,HOSTEL ROOM,Several times a week,Unable to connect to Wi-Fi,Assignments/project work
6,mess/canteen,MESS / CANTEEN,Almost every day,Frequent disconnection,Online events/hackathons
7,academic buildings/classrooms,ACADEMIC BUILDINGS,Several times a week,Unable to connect to Wi-Fi,Downloading/uploading files
8,hostel common area,HOSTEL COMMON AREA,Almost every day,Frequent disconnection,Online classes/academic work
9,hostel room,HOSTEL ROOM,Almost every day,Frequent disconnection,Downloading/uploading files
10,academic buildings/classrooms,ACADEMIC BUILDINGS,Almost every day,Slow internet speed,Downloading/uploading files
11,all places,HOSTEL ROOM,Almost every day,All of the above,Coding/development

In [22]:
location_profile = (
    survey_location
    .groupby("location_group")
    .size()
    .reset_index(name="survey_mentions")
    .sort_values("survey_mentions", ascending=False)
)

display(location_profile)

       location_group  survey_mentions
2         HOSTEL ROOM               49
0  ACADEMIC BUILDINGS               13
1  HOSTEL COMMON AREA               12
3             LIBRARY                7
4      MESS / CANTEEN                6
5               OTHER                3

In [23]:
frequency_score = {
    "Almost every day": 4,
    "Several times a week": 3,
    "Occasionally": 2,
    "Rarely": 1
}

survey_location["frequency_score"] = (
    survey_location["frequency"]
    .map(frequency_score)
)

In [24]:
frequency_profile = (
    survey_location
    .groupby("location_group")
    .agg(
        avg_frequency_score=("frequency_score", "mean")
    )
    .reset_index()
)

display(frequency_profile)

       location_group  avg_frequency_score
0  ACADEMIC BUILDINGS             3.769231
1  HOSTEL COMMON AREA             4.000000
2         HOSTEL ROOM             3.693878
3             LIBRARY             4.000000
4      MESS / CANTEEN             3.833333
5               OTHER             4.000000

In [25]:
def expand_problem(x):
    x = str(x).strip().lower()

    if "all" in x or "every" in x:
        return [
            "SLOW SPEED",
            "UNABLE TO CONNECT",
            "FREQUENT DISCONNECTION"
        ]

    if "slow" in x:
        return ["SLOW SPEED"]

    if "unable" in x or "connect" in x:
        return ["UNABLE TO CONNECT"]

    if "disconnect" in x:
        return ["FREQUENT DISCONNECTION"]

    return ["OTHER"]

In [26]:
survey_problem = survey_location.copy()

survey_problem["problem_group"] = survey_problem[
    "problem_type"
].apply(expand_problem)

survey_problem = survey_problem.explode("problem_group")

In [27]:
problem_profile = (
    survey_problem
    .groupby(["location_group", "problem_group"])
    .size()
    .reset_index(name="mentions")
)

display(
    problem_profile.sort_values(
        ["location_group", "mentions"],
        ascending=[True, False]
    )
)

        location_group           problem_group  mentions
2   ACADEMIC BUILDINGS       UNABLE TO CONNECT         9
1   ACADEMIC BUILDINGS              SLOW SPEED         8
0   ACADEMIC BUILDINGS  FREQUENT DISCONNECTION         4
5   HOSTEL COMMON AREA       UNABLE TO CONNECT         8
4   HOSTEL COMMON AREA              SLOW SPEED         7
3   HOSTEL COMMON AREA  FREQUENT DISCONNECTION         3
8          HOSTEL ROOM              SLOW SPEED        32
9          HOSTEL ROOM       UNABLE TO CONNECT        25
6          HOSTEL ROOM  FREQUENT DISCONNECTION         9
7          HOSTEL ROOM                   OTHER         1
11             LIBRARY              SLOW SPEED         5
12             LIBRARY       UNABLE TO CONNECT         5
10             LIBRARY  FREQUENT DISCONNECTION         3
15      MESS / CANTEEN       UNABLE TO CONNECT         5
14      MESS / CANTEEN              SLOW SPEED         4
13      MESS / CANTEEN  FREQUENT DISCONNECTION         3
17               OTHER              SLOW SPEED         3
16               OTHER  FREQUENT DISCONNECTION         2
18               OTHER       UNABLE TO CONNECT         2

In [28]:
impact_score = {
    "Assignments/project work": 3,
    "Downloading/uploading files": 2,
    "Online events/hackathons": 3,
    "Online classes/academic work": 3,
    "Coding/development": 3
}

In [29]:
print(survey["impact"].value_counts())

impact
Assignments/project work                    23
Online classes/academic work                15
Downloading/uploading files                 12
Coding/development                           8
Online events/hackathons                     6
All                                          2
Streaming/content consumption                2
Video calls/meetings                         2
Every above option                           1
Everything because internet doesn't work     1
all of the above                             1
It kills the vibe                            1
Name: count, dtype: int64

In [30]:
location_profile.to_csv(
    "survey_location_profile.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!